name: CI

on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [dev, main]

env:
  MIX_ENV: test

jobs:
  deps:
    name: Dependencies on OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: ["24.3.4"]
        elixir: ["1.14.2"]
    steps:
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Retrieve Cached Dependencies
        id: mix-cache
        uses: actions/cache@v3
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}

      - name: Install dependencies
        if: steps.mix-cache.outputs.cache-hit != 'true'
        run: |
          mix deps.get
          mix deps.compile

  static_code_analysis:
    name: Static code analysis on OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    needs: deps
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        otp: ["24.3.4"]
        elixir: ["1.14.2"]
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Retrieve Cached Dependencies
        id: mix-cache
        uses: actions/cache@v3
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}

      - name: Compiles without warnings
        run: mix compile --warnings-as-errors

      - name: Check Formatting
        run: mix format --check-formatted

      - name: Run Credo
        run: mix credo

  testing:
    name: Testing on OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    timeout-minutes: 15
    needs: deps
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: ["24.3.4"]
        elixir: ["1.14.2"]
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start Docker Services
        run: docker compose up -d

      - name: Retrieve Cached Dependencies
        id: mix-cache
        uses: actions/cache@v3
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}

      - name: Run tests
        run: mix test --trace
        env:
        MIX_ENV: test
